# Generated by Django 3.2.3 on 2021-11-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Business', 'Business'), ('Technology', 'Technology'), ('Travel', 'Travel')], default=None, max_length=30),
        ),
    ]
